#  conda env create --name ChIPseq_mapping --file environment.yaml 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=6.0.3
  - pandas=0.24.2
  - bbmap=38.22
  - cutadapt=1.18
  - fastqc=0.11.8
  - bowtie2=2.3.4.3
  - picard=2.18.16
  - samtools=1.10
  - deeptools=3.5.0
  - ucsc-facount=377
  - ucsc-bedgraphtobigwig=377
